Change title per Magnus Nyström's review
x509-hbs/draft-x509-shbs pull request #17
Opened 2024-10-25 07:41 UTC by danvangeest

2024-10-25 08:30 UTC, fluppe2 requested changes

2024-10-25 08:30 UTC, fluppe2 commented on draft-ietf-lamps-x509-shbs.md
> +title: "Use of the HSS and LMS Hash-Based Signature Algorithms in Internet X.509 Public Key Infrastructure"
```suggestion
title: "Use of the HSS and XMSS Hash-Based Signature Algorithms in Internet X.509 Public Key Infrastructure"
```

2024-10-25 14:47 UTC, danvangeest commented on draft-ietf-lamps-x509-shbs.md
> +title: "Use of the HSS and LMS Hash-Based Signature Algorithms in Internet X.509 Public Key Infrastructure"
Well that was dumb of me!

2024-10-29 10:04 UTC, BashiriK approved these changes

2024-10-29 10:07 UTC, fluppe2 approved these changes

2024-11-13 11:06 UTC, merged