'hit your PANIC button' isn't very helpful, try to be a bit more desc…
x509-hbs/draft-x509-shbs pull request #19
Opened 2024-10-25 15:28 UTC by danvangeest

…riptive

2024-10-29 10:12 UTC, fluppe2 commented on draft-ietf-lamps-x509-shbs.md
> +  of money trying to figure out you ended up with a OTS key reuse.
```suggestion
  if previously released signatures showed OTS key reuse).
```

The ", and spend a lot  of money trying to figure out you ended up with a OTS key reuse" might trigger a new comment, maybe it is better to omit that. The text is otherwise very clear on what to do.

2024-10-29 10:12 UTC, fluppe2 requested changes
Left a suggestion.

2024-10-29 10:22 UTC, danvangeest commented on draft-ietf-lamps-x509-shbs.md
> +  of money trying to figure out you ended up with a OTS key reuse.
I wanted to say that there should probably also be some sort of post-failure audit, although admittedly "spend a lot of money" wasn't necessary.  Do you think a sentence about a post-failure audit is useful/necessary?

2024-10-29 10:29 UTC, fluppe2 commented on draft-ietf-lamps-x509-shbs.md
> +  of money trying to figure out you ended up with a OTS key reuse.
Now I get it. Yes, definitely!

2024-10-30 12:14 UTC, danvangeest commented on draft-ietf-lamps-x509-shbs.md
> +  if previously released signatures showed OTS key reuse).
```suggestion
  if previously released signatures showed OTS key reuse), and perform a post-failure audit.
```

2024-10-30 14:15 UTC, fluppe2 approved these changes

2024-10-30 14:15 UTC, fluppe2 commented on draft-ietf-lamps-x509-shbs.md
> +  if previously released signatures showed OTS key reuse).
Perfect

2024-10-30 14:18 UTC, fluppe2 approved these changes

2024-10-30 14:27 UTC, fluppe2 approved these changes
LGTM

2024-10-30 14:28 UTC, fluppe2 approved these changes

2024-11-13 11:08 UTC, merged